"""outbox retry and quarantine columns

Revision ID: 0ffacbda7518
Revises: fbe932850694
Create Date: 2026-07-07 01:12:31.819181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ffacbda7518'
down_revision: Union[str, None] = 'fbe932850694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_outbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parked_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_outbox', schema=None) as batch_op:
        batch_op.drop_column('next_attempt_at')
        batch_op.drop_column('parked_at')

    # ### end Alembic commands ###
