"""decision outbox and citable gate

Revision ID: fbe932850694
Revises: fd6d837f3807
Create Date: 2026-07-07 01:03:12.151248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe932850694'
down_revision: Union[str, None] = 'fd6d837f3807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('violation_id', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_outbox_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_outbox_violation_id'), ['violation_id'], unique=False)

    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('citable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('gate_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.drop_column('gate_reason')
        batch_op.drop_column('citable')

    with op.batch_alter_table('decision_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_outbox_violation_id'))
        batch_op.drop_index(batch_op.f('ix_decision_outbox_created_at'))

    op.drop_table('decision_outbox')
    # ### end Alembic commands ###
