"""initial review schema

Revision ID: fd6d837f3807
Revises: 
Create Date: 2026-07-02 04:59:44.404225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6d837f3807'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('officer', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('violation_id', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_officer'), ['officer'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_row_hash'), ['row_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_seq'), ['seq'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_log_violation_id'), ['violation_id'], unique=False)

    op.create_table('camera_lanes',
    sa.Column('camera_name', sa.String(length=128), nullable=False),
    sa.Column('lane_data', sa.JSON(), nullable=False),
    sa.Column('calibration_width', sa.Integer(), nullable=False),
    sa.Column('calibration_height', sa.Integer(), nullable=False),
    sa.Column('background_frame_url', sa.Text(), nullable=False),
    sa.Column('background_frame_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('camera_name')
    )
    op.create_table('cameras',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('last_ping', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('msg', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_at'), ['at'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('jti', sa.String(length=32), nullable=False),
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('replaced_by', sa.String(length=512), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reused_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('uptime', sa.String(length=32), nullable=False),
    sa.Column('latency', sa.String(length=32), nullable=False),
    sa.Column('usage', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_status_timestamp'), ['timestamp'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('privileges', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('keybinds', sa.JSON(), nullable=False),
    sa.Column('theme', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('violations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('speed_limit', sa.Integer(), nullable=True),
    sa.Column('plate', sa.String(length=24), nullable=False),
    sa.Column('vehicle', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('cameras', sa.JSON(), nullable=False),
    sa.Column('camera', sa.String(length=64), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('weather', sa.String(length=64), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('clip_url', sa.Text(), nullable=False),
    sa.Column('raw_clip_url', sa.Text(), nullable=False),
    sa.Column('screenshot_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_violations_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_violations_status'), ['status'], unique=False)

    op.create_table('violation_reviews',
    sa.Column('violation_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('violation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violation_reviews')
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violations_status'))
        batch_op.drop_index(batch_op.f('ix_violations_date'))

    op.drop_table('violations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('system_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_status_timestamp'))

    op.drop_table('system_status')
    op.drop_table('services')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_family_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_at'))

    op.drop_table('notifications')
    op.drop_table('cameras')
    op.drop_table('camera_lanes')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_violation_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_seq'))
        batch_op.drop_index(batch_op.f('ix_audit_log_row_hash'))
        batch_op.drop_index(batch_op.f('ix_audit_log_officer'))
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
